### ISSUE TITLE
Captured contexts on Executor pool threads are lazily cleaned up 

### ISSUE THREAD

**Issue by mmusgrov** [smallrye/smallrye-concurrency#35] opened 2019-03-01 19:19 UTC
Create a CompletableFuture via a ManagedExecutor and then call join() on it. When join() returns all of the threads ran by the executor should have had there context reinstated. But the behaviour I observed is that the context is reinstated at an arbitrary time after the join() call. This is a problem for transactional code. The example I used was:

> on the main thread
    CompletableFuture<Void> stage = executor.runAsync(service::required);
    stage.join();
    userTransaction.rollback();  
> the captured context of the executor pool thread is still on the thread when the transaction rollback happens. Because of this behaviour our TM complains with a warning because the rollback call finds two thread active on the transaction.

**Comment by manovotn** [comment] 2019-03-01 20:22
Do I understand you correctly that the [`endContext()` method](https://github.com/smallrye/smallrye-concurrency/blob/master/core/src/main/java/io/smallrye/concurrency/ActiveContextState.java#L22) is called too late?

If you have the code you tried to reproduce this with on some branch, share it please.

**Comment by mmusgrov** [comment] 2019-03-03 10:51
Running a basic transaction test on the master branch should highlight the issue:

```
mvn test -f tests/pom.xml -Dtest=JTATest#testTransaction
```

The problem is that when the rollback is called here https://github.com/smallrye/smallrye-concurrency/blob/master/tests/src/test/java/io/smallrye/concurrency/test/JTATest.java#L111 the executor pool thread used on line 107 still has the transaction associated with it since the context is cleaned lazily (ie after the join call). There should be a stacktrace warning in the test output similar to:

> WARN  ARJUNA012381: Action id 0:ffffc0a80021:9a8d:5c7bb024:2 completed with multiple threads

**Comment by manovotn** [comment] 2019-03-04 14:38
Hmm, is the `JtaContextProvider` correctly clearing up the context after you are done executing the task?
Because what happens is that every task is wrapped with what the context provider does before and after the task is run and the whole task isn't completed until the `endContext()` will be invoked.

**Comment by mmusgrov** [comment] 2019-03-06 15:24
Running in the debugger I definitely see ActiveContextState#endContext being called after calling join() on the only stage of the executor ie JtaContextProvider is invoked after the join call.

Also if I put a pause after the join call then I do see the context being cleared showing that the executor threads are lazily cleaned.

**Comment by mmusgrov** [comment] 2019-03-07 07:53
If I pause in the debugger after the join() call I can see the stacktrace for the endcontext call as follows:
''' "io.smallrye.concurrency.jta.context.propagation.JtaContextProvider.suspendTransaction(JtaContextProvider.java:69)"
"io.smallrye.concurrency.jta.context.propagation.JtaContextProvider.lambda$null$0(JtaContextProvider.java:44)"
 "io.smallrye.concurrency.ActiveContextState.endContext(ActiveContextState.java:26)"
 "io.smallrye.concurrency.impl.ThreadContextImpl$ContextualRunnable.run(ThreadContextImpl.java:57)"
 "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
 "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
 "java.lang.Thread.run(Thread.java:748)"
'''

**Closed** 2019-03-07 13:18 UTC
